version: '3'
services:
  nick_bot:
    image: dockerhub.lemazo.online/discord_bot/nick_bot:latest
    restart: always
    volumes:
    - ./config:/config
    - ./nick_bot:/root/nick_bot
  mongo:
    image: mongo:4.4-rc
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - /data/mongodb:/data/db