name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Connection to Registry
      run: docker login -u=${{ secrets.DOCKER_HUB_USER }} -p=${{ secrets.DOCKER_HUB_PASSWORD }} ${{ secrets.DOCKER_HUB_HOST }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dockerhub.lemazo.online/discord_bot/nick_bot:$GITHUB_SHA
    - name: Push the Docker Image to Registry
      run: docker push dockerhub.lemazo.online/discord_bot/nick_bot:$GITHUB_SHA
