name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SHA: $GITHUB_SHA

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        registry: ${{ secrets.DOCKERHUB_HTTP_HOST }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: dockerhub.lemazo.online/discord_bot/nick_bot:latest, dockerhub.lemazo.online/discord_bot/nick_bot${{env.SHA}}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy new version
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd nick_bot
          git pull
          docker-compose down
          docker-compose pull
          docker-compose up -d
