name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Connection to Registry
      run: docker login -u=${{ secrets.DOCKERHUB_USER }} -p=${{ secrets.DOCKERHUB_PASSWORD }} ${{ secrets.DOCKERHUB_HTTP_HOST }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dockerhub.lemazo.online/discord_bot/nick_bot:$GITHUB_SHA --tag dockerhub.lemazo.online/discord_bot/nick_bot:latest
    - name: Build ARM Image
      run: docker build . --file Dockerfile --tag dockerhub.lemazo.online/discord_bot/nick_bot:arm-$GITHUB_SHA --tag dockerhub.lemazo.online/discord_bot/nick_bot:arm-latest --platform linux/arm/v7
    - name: Push the Docker Image to Registry
      run: docker push dockerhub.lemazo.online/discord_bot/nick_bot --all-tags
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy new version
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd nick_bot
          git pull
          docker-compose down
          docker-compose pull
          docker-compose up -d
